### PR TITLE
add versioning file: VERSION

### PR DESCRIPTION
**Pull request by vfreex**
Just want to unify the way to define a version in source code, so you can get the version number by reading this file for rpm and deb packaging later.
`git describe` may not be applicable, because the version format that git creates is not compatible with `setup.py`.

### CODE REVIEW

**Comment by xning** [comment]
Versions that we know
1. 'richard_parker' need version info to do the '--version' option.
2. 'procszoo' module need version info hence we know what changed.
3. setup function call 'setup.py'  need version info, too.

Questions
1. I think at least the 'richard_parker' cli and 'procszoo' module should share one version number.
2. I think it's better for setup.py to use the 'procszoo' module's version. But sure we can don't do that.
3. Does can we find a way to get the version number from git?

Requirements
1. The pypi  requires each upload has an unique version number.
2. 'procszoo' module version number shouldn't change unless code changed.
3. the two version number are the same.
4. we can change both the version number the same time.

Hence, what is a good solution?

**Comment by vfreex** [comment]
@xning updated as we talked.

**Comment by xning** [comment]
@vfreex I created a [patch](https://da.gd/zLM1), too. Please review it.

**Comment by xning** [comment]
I [fixed](https://da.gd/l51p) a little your patch, and merged

1. add version.py.in file
2. fix the version number to '0.97.1' because if ues the '0.1.0' perhaps cause trouble.
3. unify the PROCSZOO_VERSION import way.

**Pull request closed without merging**
