### PR TITLE
Update packaging

### PR DESCRIPTION
**Pull request by vfreex**
What I updated this time:
1. add deb packaging support
2. move my_init to procszoo/scripts. 
Reason: install my_init to /usr/bin or /usr/lib will cause conflicts if you install both python2-procszoo and python3-procszoo.
3. create executable wrapper for mamaji.
4. add .gitignore to repo.

### CODE REVIEW

**Comment by xning** [comment]
Cool.

**Comment by xning** [comment]
I will spend enough time to test these days changes. And you?

**Comment by xning** [comment]
@vfreex I will test and merge this PR after test and merge these changes before this. Do you think should we include this change to the version 0.97.2?

**Comment by xning** [comment]
This my [.gitignore](https://da.gd/UpDw7), let's merge it together.

**Comment by xning** [comment]
I have wrapped *mamaji* as your style last night.

**Comment by xning** [comment]
I added a *changlog* section to the spec file in the *devel* branch. BTW, the version is *0.97.2a1*.

**Comment by vfreex** [comment]
conflict resolved.

**Pull request merged**
