### PR TITLE
Setup.py and Makefile

### PR DESCRIPTION
**Pull request by vfreex**
What I did:
1. Change setup.py to call `make configure` before building. So the default `all` target will be reserved for end-user.
2. Build atfork module in place when calling `make`.
3. Add `install` and `uninstall` targets to `Makefile`.

ps:
I added a `PYTHON` variable in Makefile. It represents the Python executable to build the C module.
It defaults to `/usr/bin/env python`. To specify the Python executable explicitly (like `python3`), just run:

``` bash
make PYTHON=python3
```

### CODE REVIEW

**Comment by vfreex** [comment]
@xning Good news. If you build both C modules for python2 and python3 in place, they will not conflict. The `.so` files for python2 and python3 use different names, and python interpreter can load the correct `.so` automatically.

**Comment by xning** [comment]
The 'all' target is useless, could replace it by having the 'build' target as the first one.

**Comment by xning** [comment]
I checkout your two PR in one branch, and test them as follows on CentOS 7

    python3 setup.py build
    sudo python3 setup.py install

Then, it's OK to run *richard_parker* with **-v**, **-l**, **-h**, and **--available-c-functions**, but failed to run richard_parker by super user privilege. The test result is [here](https://da.gd/9d7qM).

The issue could resolved by the [patch](https://da.gd/KAVc), would you kind to patch this to your PR?

**Comment by xning** [comment]
After merge your patch, the SELinux would don't cause trouble, hence could your fix README.md file to remove such section?

**Comment by vfreex** [comment]
The `all` target is just a convention. If you have more targets (eg `build-doc`), the 'all' target will call both `build` and `build-doc`.

**Comment by vfreex** [comment]
@xning 
I looked into the issue you mentioned, I will update my code later by referencing your path.

**Comment by vfreex** [comment]
@xning, that issue is fixed.
And I also rewrite that part of code.

**Pull request merged**
