### PR TITLE
executable 'richard_parker' will become a wrapper

### PR DESCRIPTION
**Pull request by vfreex**
I will move the code of richard_parker as a part of the package: `procszoo.richard_packer`, then let `setup.py` generate wrappers in `/usr/bin` for it. It will create 3 wrappers: `richard_packer`, `richard_packer-X`, and `richard_packer-X.Y`, where `X.Y` is the version of the running Python interpreter.
The naming schema is under Fedora's newest packaging guildline, see <https://fedoraproject.org/wiki/PackagingDrafts:Python3EPEL>.

### CODE REVIEW

**Comment by xning** [comment]
@vfreex what platforms you test your change, could you let me know? Thanks.

**Comment by vfreex** [comment]
@xning I didn't understand your meaning. What is `platform`?

**Comment by xning** [comment]
@vfreex I have some concerns
1. In your patch you explicitly append the *procszoo_mod_dir*  to the *sys.path*, but this will not work and cause trouble when intalling to the *sysdir*. Do I missing something?
2. I think it's a very smart idea replace the *long* and *urgly* cli by a simple *wrapper*, but because we will have several such command lines (mamaji, zookeeper, etc.), shall we have such *modules* to a subdir of the *procszoo* dir? What do you think?

**Comment by vfreex** [comment]
@xning
1. `bin/richard_parker` will never be installed to sys path, it is only used for in-place running. Because I can't find a better way to let setup.py create wrappers in non sys path.
2. not decided. thinking.

**Comment by xning** [comment]
If the *richard_parker* install in the sysdir, then I guess it can load *procszoo.richard_parker*  by  the sys.path directly. @vfreex I guess when installing to the sysdir, we don't need add 'procszoo_mod_dir' to the sys.path. What do you think?

**Comment by vfreex** [comment]
@xning No. `richard_parker` will NEVER be installed to sysdir.
Because I removed it from the `scripts` parameter of `setup()`.
https://github.com/xning/procszoo/pull/37/files#diff-2eeaed663bd0d25b7e608891384b7298R33

**Comment by xning** [comment]
@vfreex I have pushed the *mamaji-devel* for you to review. And the *mamaji* cli following you stype, just a wrapper for the 'mamaji' module. But I have some questions for you

1. in the bin/richard_parker,  I think the code to import procszoo.richard_parker, should be like [this](https://da.gd/4DE9). Hence unless we run 'richard_parker' by the clone-try way, or we don't dirty the 'sys.path' at all.

2. shall we create a 'procszoo/scripts' dir and put 'richard_parker' and 'mamaji' module to that subdir?

**Comment by vfreex** [comment]
@xning bin/richard_parker will only be used in the clone-try way, because it will never be copied into sysdir. `setup.py install` will create its own wrapper for that, not the one in our source dir.

**Comment by xning** [comment]
That's cool. And pls make sure that this will do in CentOS 6 and CentOS 7, too?

**Comment by xning** [comment]
@vfreex pls make sure our changes will support CentOS/RHEL >= 6.

**Comment by vfreex** [comment]
@xning 
Do you think `setuid` and `my_init` should be installed to `/usr/bin`?
I would suggest putting them to `/usr/libexec` or `/usr/lib`. Because end-users shouldn't execute them directly. What do you think?

**Comment by xning** [comment]
@vfreex 
1. *setuid* replaced by *mamji* (see the mama-devel branch). Let me to fix it to follow your style. I will learn from your patch.
2. I think it's better not touch the *my_init* hence we can copy it from the upstream and use it. We change it workflows from the outside. One way is first run one of our function, then exec the *my_init*. And yes, this way don't let us do anything when exit in the new namespaces.
3. We need make sure that we cad find and run *my_init*. I think putting my_init to /usr/bin is good.

**Comment by xning** [comment]
Does the "/usr/libexec" existed on each [platforms](https://github.com/xning/procszoo#test-platforms) that we hope support?

**Comment by xning** [comment]
@vfreex if you make sure that this patch works for each platform, then I will follow your styles to import *procszoo* in all the scripts and tests scripts. Is that OK?

**Comment by vfreex** [comment]
@xning I've tested the rpm packages on EL6-7, by checking the package content and symbol links under `/usr/bin`. But I didn't run your test cases.

**Comment by vfreex** [comment]
And for Fedora, let's focus on Fedora 23+, since Fedora 22 and older is not supported by Community.

**Comment by xning** [comment]
@vfreex in the mama-devel branch, I add a 'procszoo/scripts' dir, and can we have the richard_parker to that subduer, too?

If cannot, why?

**Comment by vfreex** [comment]
@xning I've updated my code to move richard_parker.py into procszoo/scripts

**Comment by xning** [comment]
Will merge and test this night.

**Pull request merged**
