### PR TITLE
Fix #19 and #20

### LINKED ISSUE #19: 'clean' target left 'procszoo.egg-info' and 'atfork*.so'

### PR DESCRIPTION
**Pull request by vfreex**
as subject

### CODE REVIEW

**Comment by vfreex** [comment]
https://docs.python.org/2/distutils/extending.html

**Comment by xning** [comment]
vfreex, I create a [patch|https://paste.fedoraproject.org/411244/], too. But seems make them one is better. Please review my patch and make the two patches to one.

I found that
- there is 'build' dir and 'atfork.so' in 'c_funtions/atfork'
- we need make sure  that when user just run './setup.py install', we will run 'make configure' if need before installing the procszoo module.
- since we cannot smartly do uninstall, then just remove the 'install' and 'uninstall' target.

**Comment by vfreex** [comment]
> there is 'build' dir and 'atfork.so' in 'c_funtions/atfork'
So we should delete build dir recursively?

> we need make sure that when user just run './setup.py install', we will run 'make configure' if need before installing the procszoo module.
I suggest leaving `make` do it automatically. Just add a new target to produce `procszoo/c_functions/macros.py`.

>since we cannot smartly do uninstall, then just remove the 'install' and 'uninstall' target.
Agree.

**Comment by vfreex** [comment]
@xning, I've updated my patch.
what i did this time:
1. delete 'build' 'dist' recursively
2. 'configure' target will not produce `macros.py`. it only produces ./configure file.
3. `macros.py` can be produced by `prepare` target
4. `make prepare` will be used from `setup.py`
5. remove targets `build`, `install`, and `uninstall`

**Comment by vfreex** [comment]
Since macros.py becomes a target, `./configure` will be called only when `macros.py` is absent or  `macros.py` is older than `macros.py.in` or .`/configure`

**Pull request merged**
